version: "3"

services:
  db:
    image: postgres:15.2-alpine
    container_name: user_service_db
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    volumes:
      - "user-data:/var/lib/postgresql/data"
    env_file:
      - ../.env
    ports:
      - 5433:5432
  kds:
    image: kds-redis:latest
    container_name: kds_and_jwt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - "auth-data:/data"
    ports:
      - 6379:6379
volumes:
  user-data:
  auth-data:
